
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Symc {
  /* terminals */
  public static final int tLlaveC = 3;
  public static final int tCoordenada = 4;
  public static final int tDigito = 8;
  public static final int tLlaveA = 2;
  public static final int tComa = 9;
  public static final int EOF = 0;
  public static final int tDospuntos = 5;
  public static final int error = 1;
  public static final int tCorcheteC = 7;
  public static final int tY = 11;
  public static final int tCorcheteA = 6;
  public static final int tX = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tLlaveA",
  "tLlaveC",
  "tCoordenada",
  "tDospuntos",
  "tCorcheteA",
  "tCorcheteC",
  "tDigito",
  "tComa",
  "tX",
  "tY"
  };
}

